language: go
go:
  - 1.2
  - tip

before_install:
  - support/bootstrap-ubuntu.sh
  - go install -race std
  - go get code.google.com/p/go.tools/cmd/cover

script:
  - go test -race ./...
  - go test -cover ./...

matrix:
  allow_failures:
    - go: tip
